server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${SITE_URL:http://levelup.ddns.net:3000}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - Authorization
                  - Content-Type
                  - X-Requested-With
                  - Accept
                exposedHeaders:
                  - Location
                  - Content-Disposition
                allowCredentials: true

          routes:
            - id: authService
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            - id: userService
              uri: http://localhost:8082
              predicates:
                - Path=/users/**

            - id: productService
              uri: http://localhost:8083
              predicates:
                - Path=/products/**

            - id: cartService
              uri: http://localhost:8084
              predicates:
                - Path=/carts/**

            - id: orderService
              uri: http://localhost:8085
              predicates:
                - Path=/orders/**

            - id: billingService
              uri: http://localhost:8086
              predicates:
                - Path=/billings/**

            - id: reviewService
              uri: http://localhost:8087
              predicates:
                - Path=/reviews/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
