server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "${SITE_URL:http://localhost:8000}"
                  - "${SITE_URL:http://localhost:8080}"
                  - "${SITE_URL:http://localhost:3000}"
                  - "${SITE_URL:http://levelup.ddns.net:8000}"
                  - "${SITE_URL:http://levelup.ddns.net:8080}"
                  - "${SITE_URL:http://levelup.ddns.net}"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - X-Requested-With
                  - Accept
                exposed-headers:
                  - Location
                  - Content-Disposition
                allow-credentials: true

          routes:
            - id: gateway-actuator
              uri: http://localhost:8080
              predicates:
                - Path=/actuator/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /actuator/(?<path>.*)
                    replacement: /actuator/${path}

            - id: authService
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            - id: userService
              uri: http://localhost:8082
              predicates:
                - Path=/users/**

            - id: productService
              uri: http://localhost:8083
              predicates:
                - Path=/products/**

            - id: cartService
              uri: http://localhost:8084
              predicates:
                - Path=/carts/**

            - id: orderService
              uri: http://localhost:8085
              predicates:
                - Path=/orders/**

            - id: billingService
              uri: http://localhost:8086
              predicates:
                - Path=/billings/**

            - id: reviewService
              uri: http://localhost:8087
              predicates:
                - Path=/reviews/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, routes

logging:
  level:
    org.springframework.cloud.gateway: INFO